### ISSUE TITLE
Buffered stream from sockets not working on Windows

### ISSUE THREAD

**Issue by profwillie** [bgyori/pykqml#10]
When creating a KQMLModule, it attempts to connect to the server on the specified port.  Connecting to the port works fine, but creating the buffered streams after this are problematic on Windows.  For example, line 158 of kqml_module.py has the following line:

`fio = io.FileIO(sfn, mode='w')`

This will cause the following error output:
`INFO: KQMLModule - Using socket connection
ERROR: KQMLModule - [WinError 6] The handle is invalid
ERROR: KQMLModule - Connection failed`

I believe the issue has to do with that sfn is a file handle on windows, whereas in posix it is a file descriptor, and FileIO requires a file descriptor.

I have confirmed that everything works fine on my Mac.

**Comment by bgyori** [comment]
Thank you! We haven't tested this on Windows but your analysis of why it doesn't work makes sense. We could either find a way to generalize that part of the code to work on Windows or add explicit branching based on the platform and use something other than the `sfn` variable  for Linux/Mac. Do you have any suggestions off the top of your head?

**Comment by profwillie** [comment]
Ideally, Python would provide a way to get the file descriptor from the file handle and then everything proceeds normally.  I can't seem to find that functionality anywhere.

The alternative is to provide your own stream that the BufferedReader (and Writer) could wrap.  You'd have to explicitly read from the socket and add to the custom stream, which would then be available to the BufferedReader.  Similar process for Writer and send.

**Comment by profwillie** [comment]
I might have finally found a way to get the file descriptor on Windows.

`import msvcrt`
`sfd = msvcrt.open_osfhandle(sfn, os.O_APPEND)`
`fio = io.FileIO(fd, mode='w')`
