### ISSUE TITLE
Latest code with fixes for windows not in a release

### ISSUE THREAD

**Issue by SamuelHill** [bgyori/pykqml#14]
The latest version of the code works perfectly for my application but it has now been a year of needing to do manual setup via 'python setup.py install' and I was wondering if the latest code will make it into a release? It would be much easier to get our new people using this with a simple pip install if that is at all possible! Thanks, Sam.

**Comment by bgyori** [comment]
Absolutely, I just made new release, v1.1: https://pypi.org/project/pykqml/1.1/
